### ISSUE TITLE
Django stuff in Apache

### ISSUE THREAD

**Issue by pasajeros** [techlib/celus#10]
Can someone help me make a working connection between Apache and Celus (via module mod_wsgi_python3) ?

So far I succeeded to install Celus without errors via the playbook and I configured /opt/celus/config/settings/* for my setup. 

My <VirtualHost *:80> Apache config:
       # Django stuff - mod_wsgi
        TimeOut 300
        WSGIScriptAlias /production /opt/celus/config/production.wsgi
        WSGIScriptAlias /api /opt/celus/config/wsgi.py/api
        WSGIDaemonProcess celus python-home=/opt/virtualenvs/celus/ python-path=/opt/celus/ processes=8 threads=10
        WSGIProcessGroup celus

        <Directory /opt/celus/config>
                <Files production.wsgi>
                        Require all granted
                </Files>
        </Directory>

        # Javascript routing needs the following
        FallbackResource /noindex/index.html

        Alias /media/ /var/www/celus/media/

error.log:
[Tue May 18 10:43:53.814741 2021] [wsgi:error] [pid 13630:tid 139945342514944] [remote 172.17.0.1:48892] Not Found: /production/

Probably some more configuration needs to be done, but I don't know where to start (finish).

**Comment by beda42** [comment]
Hi,

have you tried using the exact configuration that is in the installation documentation? It should work and you can then make your adjustments starting from there.

Beda

**Comment by beda42** [comment]
We use the same setup that is in the documentation on our production servers, so there must be some other problem there.

Could you please post the whole configuration file with the Celus specific stuff matching the documentation? We could then try to find out what could be the problem.

**Comment by pasajeros** [comment]
Please find the /etc/httpd/* attached. The directory listing (incl links to modules) is:

[root@c0194e6d0b60 httpd]# ls -lR
.:
total 16
drwxr-xr-x 1 root root 4096 May 15 16:53 conf
drwxr-xr-x 1 root root 4096 May 18 13:57 conf.d
drwxr-xr-x 1 root root 4096 May 15 01:18 conf.modules.d
lrwxrwxrwx 1 root root   19 Nov  4  2020 logs -> ../../var/log/httpd
lrwxrwxrwx 1 root root   29 Nov  4  2020 modules -> ../../usr/lib64/httpd/modules
lrwxrwxrwx 1 root root   10 Nov  4  2020 run -> /run/httpd
lrwxrwxrwx 1 root root   19 Nov  4  2020 state -> ../../var/lib/httpd

./conf:
total 28
-rw-r--r-- 1 root root 11892 May 15 16:53 httpd.conf
-rw-r--r-- 1 root root 13064 Nov  4  2020 magic

./conf.d:
total 32
-rw-r--r-- 1 root root  400 Nov  4  2020 README
-rw-r--r-- 1 root root 2926 Nov  4  2020 autoindex.conf
-rw-r--r-- 1 root root 1522 May 18 13:57 celus.now.im.conf
-rw-r--r-- 1 root root 8720 Nov  4  2020 ssl.conf
-rw-r--r-- 1 root root 1252 Nov  4  2020 userdir.conf
-rw-r--r-- 1 root root  764 Nov  4  2020 welcome.conf

./conf.modules.d:
total 52
-rw-r--r-- 1 root root 3311 Nov  4  2020 00-base.conf
-rw-r--r-- 1 root root  139 Nov  4  2020 00-dav.conf
-rw-r--r-- 1 root root   41 Nov  4  2020 00-lua.conf
-rw-r--r-- 1 root root  948 Nov  4  2020 00-mpm.conf
-rw-r--r-- 1 root root  787 Nov  4  2020 00-optional.conf
-rw-r--r-- 1 root root 1073 Nov  4  2020 00-proxy.conf
-rw-r--r-- 1 root root   41 Nov  4  2020 00-ssl.conf
-rw-r--r-- 1 root root   88 Nov  4  2020 00-systemd.conf
-rw-r--r-- 1 root root  451 Nov  4  2020 01-cgi.conf
-rw-r--r-- 1 root root   45 Aug 31  2020 10-h2.conf
-rw-r--r-- 1 root root   57 Aug 31  2020 10-proxy_h2.conf
-rw-r--r-- 1 root root  231 Apr  7  2020 10-wsgi-python3.conf
-rw-r--r-- 1 root root  496 Nov  4  2020 README
[httpd-celus-now-im.zip](https://github.com/techlib/celus/files/6501755/httpd-celus-now-im.zip)

**Comment by beda42** [comment]
Going over the installation ansible playbook I realized that we did not properly update part of it which deals with static files. Some time ago we moved from storing compiled javascript in the repository to building it using Github actions. Since then it is necessary to fetch the built static files from Github and we did not put that info into the playbook.

Please, check-out the `staging` branch of Celus and try to run the playbook again. It should create more files in `/var/www/celus/static/` than there are currently.

Also I do not see any `DocumentRoot` in your `celus.now.im.conf` file, so please make it point to the `/var/www/celus/static/` directory.

The `FallbackResource` should be just `/index.html` not `/noindex/index.html`.

We will see if this helps, and possibly iterate further. Sorry for the trouble.

**Comment by pasajeros** [comment]
Thanks Beda, I cloned the staging branch:
git clone -b staging https://github.com/techlib/celus

and running the playbook fails with:

TASK [celus : unpack static files from github] ********************************************************
fatal: [celus.now.im]: FAILED! => {"changed": false, "msg": "Failure downloading https://github.com/techlib/celus/releases/download/master/html-root.tar.gz, HTTP Error 404: Not Found"}

**Comment by pasajeros** [comment]
should I change project_branch: master in vars to staging?

**Comment by pasajeros** [comment]
I now only changed 'master' into v1.0.36 in the django.yaml task file and now the playbook finishes correctly and static files are installed, also added the DocumentRoot, all good.

However going to the site redirects to /dashboard with : "Unauthorized user" - Sorry, but your user identity is not associated with any user account in this application. So there must be some final step in getting to the dashboard ...

**Comment by pasajeros** [comment]
The httpd error log : 
[Wed May 19 12:12:43.634845 2021] [wsgi:error] [pid 32000:tid 140628584941312] [remote 172.17.0.1:54850] Forbidden: /api/user/
[Wed May 19 12:12:43.770310 2021] [wsgi:error] [pid 31999:tid 140628584941312] [remote 172.17.0.1:54856] Identity: None
[Wed May 19 12:12:43.770632 2021] [wsgi:error] [pid 31999:tid 140628584941312] [remote 172.17.0.1:54856] Headers: HTTP_X_USER_ID: None; HTTP_X_FULL_NAME: None; HTTP_X_FIRST_NAME: None; HTTP_X_LAST_NAME: None; HTTP_X_USER_NAME: None; HTTP_X_MAIL: None; HTTP_X_CN: None; HTTP_X_ROLES: None; HTTP_X_IDENTITY: None
[Wed May 19 12:12:43.784816 2021] [wsgi:error] [pid 31999:tid 140628584941312] [remote 172.17.0.1:54856] Forbidden: /api/organization/

**Comment by beda42** [comment]
Sorry, for the delay, I was not available yesterday. I see you managed to change the version properly 👍.

As for the "identity is not associated with any user account" problem, this is already a sign that Celus is working.

The authentication in Celus is based on shibboleth and expects the HTTP server (Apache) to fill in the `HTTP_X_IDENTITY` HTTP header in each request with some identification of the user - usually the email address. Celus then searches its database for an Identity object connected to a know user. If it finds one, the user is let in. Otherwise the above message is displayed.

If you do not want to use shibboleth, you should still be able to log in using the admin interface located at `/wsEc67YNV2sq/`. There you can login using the admin credentials created in this step: https://celus.readthedocs.io/en/latest/install.html#creating-initial-superuser-account . After you log in, a session will be created for you and you can access the rest of Celus as the admin user.

**Comment by pasajeros** [comment]
I deleted the superuser (in python manage.py shell) and recreated a new one with python manage.py createsuperuser (both in virtual environment). Now I used a password with only characters and numbers, but still I'm no able to login.

Maybe we can have a zoom or teams call to see how to solve this?

**Comment by pasajeros** [comment]
BTW:
I did add :
```
        <Directory /opt/celus/config>
                <Files wsgi.py>
                        Require all granted
                </Files>
        </Directory>
```
to the virtualhost config otherwise I cannot access `/wsEc67YNV2sq`

**Comment by beda42** [comment]
I just realized that there is one more thing necessary to make the username/password authentication work.  You need to make a small change to the `config/settings/base.py` file to activate this type of authentication. There should be a part like this:

```
AUTHENTICATION_BACKENDS = [
    'apps.core.auth.EDUIdAuthenticationBackend',
    # 'django.contrib.auth.backends.ModelBackend',
]
```

You need to uncomment the line containing 'django.contrib....', so that it reads:

```
AUTHENTICATION_BACKENDS = [
    'apps.core.auth.EDUIdAuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
]
```

After restarting uwsgi, it should work.

**Comment by pasajeros** [comment]
Yesss, that was the final thing. Thanks !
