### ISSUE TITLE
Prerequisites RHEL/CentOS 8.0

### ISSUE THREAD

**Issue by pasajeros** [techlib/celus#9]
What exactly need to be installed on the server before installing Celus?
(python3-devel , gcc, .....)

I'm trying to install Celus on a Centos-8 server in a container (docker). I'm progressing however now I run into a systemctl permission issue with postgresql:

### playbook output :

PLAY [all] **************************************************************************************************

TASK [Gathering Facts] **************************************************************************************
ok: [celus.now.im]

TASK [celus : make sure some basic applications are installed] **********************************************
ok: [celus.now.im]

TASK [celus : start the redis server] ***********************************************************************
ok: [celus.now.im]

TASK [celus : ensure virtualenv and helpers are installed] **************************************************
ok: [celus.now.im]

TASK [celus : activate virtualenvwrapper] *******************************************************************
ok: [celus.now.im]

TASK [celus : get project source files from git] ************************************************************
ok: [celus.now.im]

TASK [celus : install project python dependencies into virtualenv] ******************************************
ok: [celus.now.im]

TASK [celus : ensure PostgreSQL is installed] ***************************************************************
ok: [celus.now.im]

TASK [celus : initialize the PostgreSQL cluster] ************************************************************
skipping: [celus.now.im]

TASK [celus : ensure PostgreSQL contrib package is installed] ***********************************************
changed: [celus.now.im]

TASK [celus : make sure PostgreSQL is running] **************************************************************
fatal: [celus.now.im]: FAILED! => {"changed": false, "msg": "Unable to start service postgresql: Job for postgresql.service failed because the control process exited with error code.\nSee \"systemctl status postgresql.service\" and \"journalctl -xe\" for details.\n"}

PLAY RECAP **************************************************************************************************
celus.now.im               : ok=9    changed=1    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   

### journalctl -xe output

-- Unit postgresql.service has begun starting up.
May 12 14:32:02 c0194e6d0b60 systemd[1]: systemd-journald.service: Failed to add fd to store: Operation not permitted
May 12 14:32:02 c0194e6d0b60 postgresql-check-db-dir[1031]: Directory "/var/lib/pgsql/data" is missing or empty.
May 12 14:32:02 c0194e6d0b60 postgresql-check-db-dir[1031]: Use "/usr/bin/postgresql-setup --initdb"
May 12 14:32:02 c0194e6d0b60 postgresql-check-db-dir[1031]: to initialize the database cluster.
May 12 14:32:02 c0194e6d0b60 postgresql-check-db-dir[1031]: See /usr/share/doc/postgresql/README.rpm-dist for more information.
May 12 14:32:02 c0194e6d0b60 systemd[1]: postgresql.service: Control process exited, code=exited status=1
May 12 14:32:02 c0194e6d0b60 systemd[1]: postgresql.service: Failed with result 'exit-code'.
-- Subject: Unit failed

**Comment by beda42** [comment]
Hello,

at first, please when you post a question, do not change it into something completely different afterwards. I just spent 15 minutes trying to find a solution for your encoding problem just to find out that the question is no longer relevant :(

It is much better to close the original question/issue and add a new one.

As for your question, the ansible playbook we provide should take care of installing all required packages. The problem here seems to be that postgresql is already installed, but the cluster is not initialized. The playbook installs PostgreSQL and then initializes the cluster, but only if the package was actually installed by the previous step (see the `when: pg_status.changed` condition below). If postgresql was already installed, it does not try to initialize the cluster as it assumes it is already initialized from previous runs.

```
- name: ensure PostgreSQL is installed
  dnf: name=postgresql-server state=latest
  register: pg_status

- name: initialize the PostgreSQL cluster
  command: postgresql-setup --initdb
  when: pg_status.changed
```

So the solution is either to uninstall PostgreSQL before running the playbook, or initialize the cluster manually.

I hope it helps.

Cheers
Beda

**Comment by pasajeros** [comment]
Thanks beda,
Apologies for changing the 1st question, I was progressing with the installation after posting. Next time I will close and post a new one.

This PostgreSQL issue was indeed solved by uninstalling and running the playbook again.
